apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-bookmarks
data:
  bookmarks.yaml: |
    ---
    # For configuration options and examples:
    # https://gethomepage.dev/configs/bookmarks

    - Transports & Réservations:
      - 12Go Asia:
          - abbr: 12G
            href: https://12go.asia/
      - Agoda:
          - abbr: AG
            href: https://www.agoda.com/
      - Booking:
          - abbr: BK
            href: https://www.booking.com/

    - Utilitaires:
      - Convertisseur EUR/THB:
          - abbr: THB
            href: https://www.xe.com/currencyconverter/convert/?Amount=1&From=EUR&To=THB
      - Google Translate:
          - abbr: GT
            href: https://translate.google.com/?sl=auto&tl=th&op=translate