apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "$(MY_POD_IP):3000,localhost:30007"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: bookmarks
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: services
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: settings
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: widgets
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: docker
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: kubernetes
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: proxmox
              mountPath: /app/config/proxmox.yaml
              subPath: proxmox.yaml
            - name: custom-css
              mountPath: /app/config/custom.css
              subPath: custom.css
            - name: custom-js
              mountPath: /app/config/custom.js
              subPath: custom.js
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: bookmarks
          configMap:
            name: homepage-bookmarks
        - name: services
          configMap:
            name: homepage-services
        - name: settings
          configMap:
            name: homepage-settings
        - name: widgets
          configMap:
            name: homepage-widgets
        - name: docker
          configMap:
            name: homepage-docker
        - name: kubernetes
          configMap:
            name: homepage-kubernetes
        - name: proxmox
          configMap:
            name: homepage-proxmox
        - name: custom-css
          configMap:
            name: homepage-custom-css
        - name: custom-js
          configMap:
            name: homepage-custom-js
        - name: logs
          emptyDir: {}