apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
data:
  settings.yaml: |
    ---
    title: Compagnon de Voyage — Thaïlande
    theme: dark
    color: teal

    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey
