apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
data:
  settings.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/settings/

    title: Dashboard Louis Cauvet
    theme: dark
    color: slate

    providers:
      openweathermap: openweathermapapikey
      weatherapi: weatherapiapikey
