apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
data:
  widgets.yaml: |
    ---
    - greeting:
        text_size: 2xl
        text: "Mon compagnon de Voyage — Thaïlande"

    - greeting:
        text_size: sm
        text: "🕐 Bangkok (UTC+7)"

    - datetime:
        text_size: l
        locale: fr-FR
        format:
            dateStyle: full
            timeStyle: short
            hourCycle: h23
            timeZone: Asia/Bangkok

    - openmeteo:
        label: Bangkok
        latitude: 13.7563
        longitude: 100.5018
        timezone: Asia/Bangkok
        units: metric

    - openmeteo:
        label: Chiang Mai
        latitude: 18.7883
        longitude: 98.9853
        timezone: Asia/Bangkok
        units: metric

    - openmeteo:
        label: Phuket
        latitude: 7.8804
        longitude: 98.3922
        timezone: Asia/Bangkok
        units: metric

    - openmeteo:
        label: Koh Samui
        latitude: 9.5120
        longitude: 100.0136
        timezone: Asia/Bangkok
        units: metric

    - openmeteo:
        label: Krabi
        latitude: 8.0863
        longitude: 98.9063
        timezone: Asia/Bangkok
        units: metric

    - search:
        provider: duckduckgo
        showSearchSuggestions: true
        target: _blank