apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
data:
  widgets.yaml: |
    ---
    # For configuration options and examples:
    # https://gethomepage.dev/configs/info-widgets/

    - datetime:
        text: Heure locale (Bangkok)
        timezone: Asia/Bangkok

    - openmeteo:
        label: Bangkok
        latitude: 13.7563
        longitude: 100.5018
        timezone: Asia/Bangkok
        units: metric

    - openmeteo:
        label: Chiang Mai
        latitude: 18.7883
        longitude: 98.9853
        timezone: Asia/Bangkok
        units: metric
        
    - openmeteo:
        label: Phuket
        latitude: 7.8804
        longitude: 98.3922
        timezone: Asia/Bangkok
        units: metric

    - search:
        provider: google
        showSearchSuggestions: true
        target: _blank