---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Dev:
    - Mon site local:
        href: http://localhost:3000/
        description: Mon site local

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Calendar:
    - Calendar :
        widget:
            type: calendar
            view: monthly
